FROM node:22.7.0-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json tsconfig*.json ./
# if you have a root tsconfig.base.json, copy that too

RUN npm ci

COPY . .

RUN npm install -g nodemon

ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3001

CMD ["npm",  "--prefix", "apps/backend", "run", "start:dev"]
