FROM node:22.7.0-alpine AS builder
WORKDIR /usr/src/app

COPY package*.json ./
COPY apps/backend/package.json apps/backend/

RUN npm ci

COPY apps/backend/package.json apps/backend/
COPY apps/backend/tsconfig*.json apps/backend/

COPY tsconfig*.json ./
COPY apps/backend/tsconfig*.json apps/backend/
COPY . .
RUN npm run build:backend

FROM node:22.7.0-alpine AS runner
WORKDIR /usr/src/app

ENV NODE_ENV=development

COPY --from=builder /usr/src/app/apps/backend/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY apps/backend/package.json ./

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
