name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['22.7.0']

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Lint all workspaces
              run: npm run lint

            - name: Shutdown Ubuntu MySQL
              run: sudo service mysql stop

            - name: Setup MariaDB
              uses: getong/mariadb-action@v1.11
              with:
                  mysql database: 'gamestats'
                  mysql user: ${{ secrets.DB_USER }}
                  mysql password: ${{ secrets.DB_PASS }}

            - name: Run Kafka KRaft Broker
              uses: spicyparrot/kafka-kraft-action@v1.1.0
              with:
                  kafka-version: '4.0.0'

            - name: Build backend
              run: npm run build:backend

            - name: Build frontend
              run: npm run build:frontend

            - name: Run backend tests
              run: npm run test
